name: Deploy staging to /stg

on:
  push:
    branches: [ main ]

permissions:
  contents: write


jobs:
  build-and-publish-stg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: npm ci

      - name: Build
        run: |
          npm run build
          # SPA fallback (CRA). For Vite, use: cp dist/index.html dist/404.html
          cp build/index.html build/404.html

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          persist-credentials: true

      - name: Update /stg with latest build
        shell: bash
        run: |
          rm -rf gh-pages/stg
          mkdir -p gh-pages/stg
          cp -r build/* gh-pages/stg/
          touch gh-pages/.nojekyll
          cd gh-pages
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git -c user.name="github-actions[bot]" \
                -c user.email="41898282+github-actions[bot]@users.noreply.github.com" \
                commit -m "Update staging from ${GITHUB_SHA}"
            git push origin gh-pages
          fi
