name: Promote staging to prod

on:
  workflow_dispatch: {}  # manual button in the Actions tab

permissions:
  contents: write        # allow pushing to gh-pages

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}  # required to push

      - name: Promote /stg to /
        shell: bash
        run: |
          set -euo pipefail
          cd gh-pages

          # safety: ensure stg exists and has an index.html
          test -f stg/index.html || { echo "stg build not found"; exit 1; }

          # keep .git and stg, wipe everything else at root
          shopt -s extglob dotglob
          rm -rf !(stg|.git)

          # copy stg into root (prod)
          cp -r stg/* .

          touch .nojekyll
          git add -A
          if git diff --cached --quiet; then
            echo "Nothing to promote."
          else
            git -c user.name="github-actions[bot]" \
                -c user.email="41898282+github-actions[bot]@users.noreply.github.com" \
                commit -m "Promote staging to prod"
            git push origin gh-pages
          fi
